spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://otto.db.elephantsql.com/ukgouajq
    username: ukgouajq
    password: GH1YI7-jzkTOaATG1T9OTzxIvSUNR9WW

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem